debug = false
random_seed = 31415

[model]
num_basis = 10 

[data]
num_features = 1
num_samples = 50
sigma_noise = 0.1

[training]
batch_size = 16
num_iters = 300
learning_rate = 0.1

[plotting]
output_dir = "artifacts"
figsize = [5, 3]
dpi = 200
